save:
  psql:
    use: false
    connection: 'postgresql://localhost:5432/seasons?user=seasons&password=seasons'
  pretty: false
tag:
  server: '&8[&2SE&8]'
region:
  visitor: 'visitor'
  spawn: 'spawn'