name: ${project.name}
main: com.playseasons.PlaySeasonsPlugin
version: ${project.version}
description: ${project.description}
authors: [HmmmQuestionMark]
depend: [Chitchat, WorldGuard]
commands:
  season:
    usage: /season
    aliases: [seasons, s]
  psdebug:
    usage: /psdebug
  invite:
    usage: /invite [player]
  trust:
    usage: /trust [player]
  spawn:
    usage: /spawn
  visiting:
    usage: /visiting
    aliases: [vspawn]
permisions:
  seasons.admin:
    default: op
  seasons.chat.mod:
    default: false
  seasons.chat.modplus:
    default: false
  seasons.chat.admin:
    default: false
  seasons.bypasslock:
    default: op
